### ISSUE TITLE
Create a `pkg-config` wrapper which defers to the system `pkg-config` in case it doesn't find a result

### ISSUE THREAD

**Issue by rgommers** [pypackaging-native/pkgconf-pypi#2]
If a user or a build tool runs something like:
```
$ pkg-config --cflags mylib
```
Then if `mylib.pc` is found, return the return. If it's not found, try calling the system `pkg-config` with the same arguments and return the result and exit code of that. This ensures correct "layering"; active Python environment first, system libraries after.

**Comment by virtuald** [comment]
I think for a general user trying to build a package, this seems like a reasonable thing.

However, as someone who wants to distribute packages that only link to other wheels, I definitely don't want to accidentally link to something on the system -- presumably if the package isn't found, then I forgot to include it in `build-system.requires`?

To accommodate this, can we add an environment variable should be added to prevent using the system pkgconf?

**Comment by rgommers** [comment]
@virtuald thanks, that seems like a reasonable thing to add. Could you please open a separate new issue for this?
