### ISSUE TITLE
Add release CI with cibuildwheel

### ISSUE THREAD

**Issue by rgommers** [pypackaging-native/pkgconf-pypi#9]
Given that builds are really fast, it may make sense to support all platforms that `cibuildwheel` supports and can be uploaded to PyPI. As long as that's easy of course; platforms like `i668`, `universal2`, `s390x` and `ppc64` (the more niche version, not `ppc64le`) can be left out.

It may then make sense to set up trusted publishing, with a dedicated environment with a manual approval step as described under https://docs.pypi.org/trusted-publishers/security-model/#provider-specific-considerations.

**Comment by FFY00** [comment]
Finally done.

https://pypi.org/project/pkgconf/2.1.1.post6/#files

**Comment by rgommers** [comment]
Nice work @FFY00, thanks for getting this over the finish line!
